### ISSUE TITLE
Authentication

### ISSUE THREAD

**Issue by bymaximus** [Sammaye/MongoYii#207]
No mongo authentication feature?

**Comment by yelunightroad** [comment]
how can i authentication with admin db but connect annother db?

**Comment by Sammaye** [comment]
Ironically I actually put that into the php7 edition of this ext but I
don't think I ever ported it over to this one since it requires some config
and code change.

But you could, in theory, change some functions like getDbConnection()
(since auth works per connection) and add a clause to connect to the adin
db and provide your username and password.
