### ISSUE TITLE
MongoYii converts integer strings to integer type automatically.

### ISSUE THREAD

**Issue by idutta2007** [Sammaye/MongoYii#255]
I have a field named serial_no in one of my model which is basically a string.  The search method on this model works fine as long as serial_no is NOT set to an integer. If serial  number is set to an integer  value, the partial match for the serial_no field does not work.

   Is there a way to stop the automatic conversion of an integer string to an integer value for a document in MongoYii? Looking at the documentation I could not find a way to do it.

**Comment by Sammaye** [comment]
Hmm, it is true I did not foresee such an occurrence when I made that functionality.

This is the problem with MongoDB having no data type strictness. Even now I still use that since I cannot state with certainty that ints put into the console will actually be ints when they come out into PHP (JS data typing).

Hmm, is it too much to, in beforeSave() convert them to string?

**Comment by idutta2007** [comment]
It can be done beforeSave but I have to change almost every model to cast from integer to string. That may be a lot of models to change. Instead I am thinking, I will have a base document (model) and override the setAttributes method in that base document and derive all documents(models) from the base document.

**Comment by Sammaye** [comment]
The latter way sounds good
