### ISSUE TITLE
"mongo" PECL package deprecated

### ISSUE THREAD

**Issue by ksowa** [Sammaye/MongoYii#257]
As the "mongo" PECL package became deprecated, is it possible to change your module's requirement to "mongodb" instead?

https://pecl.php.net/package/mongo

https://pecl.php.net/package/mongodb

**Comment by Sammaye** [comment]
Yes, however, the replacement is namespace only in which case you should probably move over to Yii2 to take full advantage of that. Not only that but they deprecated the old one too soon, the new driver and it's tools are not really up to scratch nor well documented yet.

To use the new extension would take a fair rewriting of this extension, plus I would need to house it in a different repo since it is completely incompatible with previous drivers and would require vastly different logic at times.

I am going to close due to that. Most have moved onto Yii2 now and those that stay on Yii1 normally do because of legacy apps.

If more demand comes for this then I will do something about it.
