### ISSUE TITLE
How to handle subdocument without named fields?

### ISSUE THREAD

**Issue by kuzdo696** [Sammaye/MongoYii#259]
Hello again,

Now I have problem with handling subdocuments, which hasn't a named fields, like:
```json
{
  _id : "something",
  name: "something_too",
  subdoc: {
    key1: "value1",
    key2: "value2"
  }
}
```
And that keys are not static fields, key can be any text. How I should handle that type of subdocuments?

Regards

**Comment by Sammaye** [comment]
Wow, I so seemed to forget about this, sorry about that.

Yeah, this is why I did not automate subdocuments in this ext, there will always be a method of nesting that doesn't fit the group.

Normally, for operators sake you would actually transform this sub into:
```
sub: [
    {key: 'key1', 'value': 'vlaue1'}
]
```
Since that is what MongoDB prefers when you query it.

But if you are determined to carry on with this then you will definitely need to define this yourself.

I cannot see any easy way to this automated in the ext nor any ext I can think of.

**Comment by Sammaye** [comment]
Since this has aged I am going to close it
